name: SOS2526 Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Start Server and Run Tests
        run: |
          # 1. Arrancamos el servidor en segundo planoo
          node index.js &
          
          # 2. Esperamos un máximo de 20 segundos a que el puerto de tu API esté listo.
          # (Si tu API no devuelve nada en la raíz "/", cámbialo por una ruta que sepas que funciona, como la de tu API)
          npx wait-on -t 30000 http://localhost:8080/api/v1/happiness-indices http://localhost:8080/api/v1/population-densities http://localhost:8080/api/v1/minimum-interprofessional-wages
          # 3. Lanzamos todas las pruebas (el comando clave que pide tu profesor)
          npm test


       